### ISSUE TITLE
Misaligned name in Team-data.md

### ISSUE THREAD

**Issue by desya42** [barrycumbie/jobie-19#56]
there is a entry in team data that is misaligned

**Comment by desya42** [comment]
entry has been fixed

**Comment by barrycumbie** [comment]
Yo @desya42 I appreciate your proactiveness to identify, issue-fy (I just made that word up! Oh darn, its the name of a financial services company), rectify, & closify? the issues.

Now, I'm reopening because I want you to do it again...since these are such easy changes it is the perfect chance for you to try and do a change to our codebase (however teeny tiny) by way of 

1. make & take ("assign self") to an issue, label it, milestone it, write some notes on it.
2. git set up (clone or pull, create branch iss47 (where 47 is the issue number), do your changes on that (git add then commit -m "" then git push) 
3. This should create the PR of which I will review and approve and merge maybe....or not.

**Comment by barrycumbie** [comment]
Oh, ask @Quanny36 he's done this.
